package com.sambas.fagiollogs.core.navigation

import android.os.Parcelable
import androidx.lifecycle.SavedStateHandle
import androidx.navigation.NamedNavArgument
import androidx.navigation.NavBackStackEntry
import androidx.navigation.navArgument

/**
 * A navigation destination with arguments.
 */
public abstract class NavDestinationWithArgs<ArgType : Parcelable> : NavigationNodeNew {

    private val routeWithoutArgs = generateRoute()

    internal val argsKey: String = "__data__"

    /**
     * The route of this destination. This is autogenerated by default.
     */
    override val route: NavRoute = NavRouteBuilder(routeWithoutArgs.value)
        .addQueryParameterPlaceholder(argsKey)
        .build()

    /**
     * Build the route to navigate to this destination with the given arguments.
     */
    public open fun navigationUri(args: ArgType): NavUriWithArgs<ArgType> {
        val data = BaseParcelableNavType.encodeParcelable(args)
        val navigationUri = NavUriBuilder(routeWithoutArgs.value)
            .addQueryParameter(argsKey, data)
            .build()
            .uri
        return NavUriWithArgs(navigationUri, args, argsKey)
    }

    /**
     * Extract the arguments of this destination from the given [NavBackStackEntry].
     */
    public open fun getArgs(navBackStackEntry: NavBackStackEntry): ArgType =
        BaseNavArgs.get(this, navBackStackEntry)

    /**
     * Extract the arguments of this destination from the given [SavedStateHandle].
     */
    public open fun getArgs(savedStateHandle: SavedStateHandle): ArgType =
        BaseNavArgs.get(this, savedStateHandle)

    /**
     * A list of all the arguments of this node.
     */
    override val arguments: List<NamedNavArgument> = listOf(
        navArgument(argsKey) {
            nullable = true
            type = BaseParcelableNavType<ArgType>()
        },
    )
}