package com.sambas.fagiollogs.core.navigation

import androidx.navigation.NamedNavArgument

/**
 * A navigation destination without arguments.
 */
public abstract class NavDestination : NavigationNodeNew {

    /**
     * The route of this destination. This is autogenerated by default.
     */
    override val route: NavRoute = generateRoute()

    /**
     * Build the route to navigate to this destination.
     */
    public open fun navigationUri(): NavUri = NavUri(route.value)

    /**
     * A list of all the arguments of this node.
     */
    override val arguments: List<NamedNavArgument> = emptyList()
}