package com.sambas.fagiollogs.core.navigation

import androidx.navigation.NamedNavArgument

interface NavigationNodeNew {
    /**
     * The route of this destination. This is autogenerated by default.
     */
    public val route: NavRoute

    /**
     * A list of all the arguments of this node.
     */
    public val arguments: List<NamedNavArgument>
}